const SAVE_KEY = "garage_tycoon_v1";
const OFFLINE_CAP = 8 * 60 * 60;
const COMBO_WINDOW = 1600;
const SPECIAL_WINDOW = 10000;

let ysdk = null;
let gameplayActive = false;
let audioContext = null;
let state = defaultState();

const WORKSHOPS = [
  { icon: "🔧", name: "Верстак", desc: "Первый мастер на смене", base: 30, growth: 1.16, rate: 1 },
  { icon: "🛠️", name: "Подъёмник", desc: "Ремонт идёт быстрее", base: 240, growth: 1.18, rate: 6 },
  { icon: "🚙", name: "Ремонтный бокс", desc: "Поток постоянных клиентов", base: 1800, growth: 1.21, rate: 35 },
  { icon: "🏭", name: "Автомастерская", desc: "Команда механиков", base: 14000, growth: 1.24, rate: 210 },
  { icon: "🏢", name: "Автоцентр", desc: "Премиальные заказы", base: 130000, growth: 1.27, rate: 1400 }
];
const CARS = [
  { name: "Старая Ласточка", icon: "🚗", parts: 120, bonus: .15, rarity: "Обычная", color: "#cfd9de" },
  { name: "Городской Зверь", icon: "🚙", parts: 500, bonus: .3, rarity: "Улучшенная", color: "#77d9a0" },
  { name: "Турбо X", icon: "🏎️", parts: 2200, bonus: .6, rarity: "Редкая", color: "#7db8ff" },
  { name: "Фантом GT", icon: "🏁", parts: 9000, bonus: 1, rarity: "Эпическая", color: "#d493ff" },
  { name: "Комета", icon: "🚀", parts: 40000, bonus: 1.65, rarity: "Легендарная", color: "#ffc83d" }
];
const EVOLUTIONS = [
  { at: 0, name: "СТАРЫЙ ГАРАЖ", sub: "Один подъёмник, одна мечта — стать автоимперией." },
  { at: 10000, name: "МАСТЕРСКАЯ", sub: "Инструменты на стене, клиенты уже в очереди." },
  { at: 100000, name: "АВТОСЕРВИС", sub: "В гараже шумят моторы и работает команда." },
  { at: 1000000, name: "АВТОЦЕНТР", sub: "Пора открывать отделение для дорогих машин." },
  { at: 10000000, name: "АВТОКОМПЛЕКС", sub: "Твой логотип знают во всём городе." }
];
const ACHIEVEMENTS = [
  ["🔨", "Первый ремонт", "Отремонтировать первую машину", () => state.totalClicks >= 1],
  ["🏭", "Автоматизация", "Купить первый подъёмник", () => state.workshops[1] >= 1],
  ["🚗", "Коллекционер", "Собрать первый автомобиль", () => state.cars.some(Boolean)],
  ["⚡", "Идеальный мастер", "Сделать идеальную сборку", () => state.perfectAssemblies >= 1],
  ["📋", "Надёжный сервис", "Закрыть заказ", () => state.ordersDone >= 1],
  ["💰", "Первый миллион", "Заработать 1M ₽", () => state.totalEarned >= 1000000],
  ["🏆", "Новый филиал", "Открыть первый филиал", () => state.prestige >= 1]
];

function defaultState() { return { money: 0, parts: 0, clickPower: 1, critLevel: 0, coolLevel: 0, workshops: [0, 0, 0, 0, 0], technologies: [0, 0, 0], cars: [false, false, false, false, false], carQuality: [0, 0, 0, 0, 0], prestige: 0, totalEarned: 0, totalClicks: 0, combo: 1, comboUntil: 0, boostUntil: 0, lastSave: Date.now(), lastDaily: "", lastCrate: 0, achievements: [], sound: true, ordersDone: 0, perfectAssemblies: 0, specialUntil: 0, specialCooldown: 0 }; }
const $ = id => document.getElementById(id);
const clamp = (n, a, b) => Math.max(a, Math.min(b, n));
const fmt = n => { if (!Number.isFinite(n)) return "0"; if (n < 1000) return Math.floor(n).toString(); const u = ["K", "M", "B", "T", "Qa"]; let i = -1; while (n >= 1000 && i < u.length - 1) { n /= 1000; i++; } return `${n.toFixed(n >= 100 ? 0 : n >= 10 ? 1 : 2)}${u[i]}`; };
const today = () => new Date().toISOString().slice(0, 10);
const workshopPrice = i => Math.floor(WORKSHOPS[i].base * Math.pow(WORKSHOPS[i].growth, state.workshops[i]));
const powerPrice = () => Math.floor(35 * Math.pow(1.65, state.clickPower - 1));
const critPrice = () => Math.floor(750 * Math.pow(1.9, state.critLevel));
const coolPrice = () => Math.floor(1000 * Math.pow(2, state.coolLevel));
const techPrice = i => Math.floor((2000 + i * 1200) * Math.pow(1.75, state.technologies[i]));
const prestigeCost = () => 1000000 * Math.pow(8, state.prestige);
const garageLevel = () => Math.floor(Math.sqrt(state.totalEarned / 1000)) + 1;
const nextLevelAt = () => Math.pow(garageLevel(), 2) * 1000;
function carBonus() { return state.cars.reduce((sum, owned, i) => sum + (owned ? CARS[i].bonus * (1 + state.carQuality[i]) : 0), 0); }
function multiplier() { return (1 + state.prestige * .25 + carBonus() + state.technologies[0] * .08 + state.technologies[1] * .05 + state.technologies[2] * .03) * (Date.now() < state.boostUntil ? 3 : 1); }
function income() { return WORKSHOPS.reduce((sum, w, i) => sum + w.rate * state.workshops[i], 0) * multiplier(); }
function clickValue() { return state.clickPower * multiplier(); }
function currentEvolution() { return EVOLUTIONS.filter(e => state.totalEarned >= e.at).at(-1); }
function nextEvolution() { const e = currentEvolution(); return EVOLUTIONS[EVOLUTIONS.indexOf(e) + 1]; }
function order() { const tier = Math.min(3, Math.floor(state.totalEarned / 25000)); const targets = [60, 180, 550, 1600]; return { name: ["Срочная диагностика", "Замена двигателя", "VIP-заказ", "Гоночный прототип"][tier], text: ["Клиент ждёт быстрый ремонт.", "Нужны детали для полного обслуживания.", "Богатый клиент хочет машину сегодня.", "Собери детали для тестового авто."][tier], need: targets[tier], reward: targets[tier] * (22 + tier * 12), partReward: 12 + tier * 18 }; }

function normalize() { state.workshops = [...(state.workshops || []), 0, 0, 0, 0, 0].slice(0, 5); state.technologies = [...(state.technologies || []), 0, 0, 0].slice(0, 3); state.cars = [...(state.cars || []), false, false, false, false, false].slice(0, 5); state.carQuality = [...(state.carQuality || []), 0, 0, 0, 0, 0].slice(0, 5); state.achievements ||= []; }
function load() { try { const saved = JSON.parse(localStorage.getItem(SAVE_KEY)); if (saved && typeof saved === "object") state = { ...state, ...saved }; } catch (error) { console.warn("Не удалось загрузить сохранение", error); } normalize(); const seconds = clamp((Date.now() - state.lastSave) / 1000, 0, OFFLINE_CAP); const gain = income() * seconds; if (gain > 1) { state.money += gain; state.totalEarned += gain; setTimeout(() => openModal("offline", { seconds, gain }), 300); } }
function save() { state.lastSave = Date.now(); localStorage.setItem(SAVE_KEY, JSON.stringify(state)); }
async function initYandexSDK() { try { if (!window.YaGames) return; ysdk = await window.YaGames.init(); ysdk.features?.LoadingAPI?.ready(); startGameplay(); } catch (error) { console.warn("Yandex SDK недоступен", error); } }
function startGameplay() { if (!gameplayActive) { ysdk?.features?.GameplayAPI?.start(); gameplayActive = true; } }
function stopGameplay() { if (gameplayActive) { ysdk?.features?.GameplayAPI?.stop(); gameplayActive = false; } }

function addMoney(amount) { if (amount <= 0) return; state.money += amount; state.totalEarned += amount; checkAchievements(); }
function click(event) { const now = Date.now(); state.combo = now < state.comboUntil ? Math.min(10, state.combo + 1) : 1; state.comboUntil = now + COMBO_WINDOW; const crit = Math.random() < Math.min(.35, .04 + state.critLevel * .025); const gain = clickValue() * state.combo * (crit ? 8 : 1); addMoney(gain); state.parts += Math.max(1, Math.floor(state.combo / 3)); state.totalClicks++; const rect = $("clicker").getBoundingClientRect(); floatText(`${crit ? "КРИТ! +" : "+"}${fmt(gain)} ₽`, event?.clientX || rect.left + rect.width / 2, event?.clientY || rect.top + rect.height / 2, crit); beep(crit ? 920 : 380 + state.combo * 20, crit ? .1 : .03); maybeSpecial(now); save(); render(); }
function buyWorkshop(i) { const price = workshopPrice(i); if (state.money < price) return toast(`Нужно ${fmt(price)} ₽`); state.money -= price; state.workshops[i]++; toast(`${WORKSHOPS[i].icon} ${WORKSHOPS[i].name}: уровень повышен`); beep(720, .06); save(); render(); }
function buyUpgrade(kind) { const config = { power: [powerPrice, "clickPower"], crit: [critPrice, "critLevel"], cool: [coolPrice, "coolLevel"] }; const [priceFn, key] = config[kind]; const price = priceFn(); if (state.money < price) return toast(`Нужно ${fmt(price)} ₽`); state.money -= price; state[key]++; toast("🔧 УЛУЧШЕНИЕ УСТАНОВЛЕНО"); beep(760, .07); save(); render(); }
function claimDaily() { if (state.lastDaily === today()) return toast("Смена уже получена — возвращайся завтра"); const money = Math.max(150, clickValue() * 50 + income() * 90); const parts = 20 + state.prestige * 10; addMoney(money); state.parts += parts; state.lastDaily = today(); toast(`🎁 СМЕНА: +${fmt(money)} ₽ и ${parts} 🔩`); save(); render(); }
function claimCrate() { if (Date.now() - state.lastCrate < 3 * 60 * 60 * 1000) return toast("Поставка в пути — возвращайся позже"); const parts = Math.max(35, Math.floor(income() * 12 + 35)); state.parts += parts; state.lastCrate = Date.now(); toast(`📦 ДОСТАВКА: +${parts} запчастей`); beep(820, .08); save(); render(); }
function showRewarded(reward) { if (!ysdk?.adv?.showRewardedVideo) { toast("Видео-награды доступны в Яндекс Играх"); return; } stopGameplay(); ysdk.adv.showRewardedVideo({ callbacks: { onRewarded: () => { if (reward === "turbo") { state.boostUntil = Date.now() + 60000; toast("⚡ ТУРБО ×3 НА 60 СЕКУНД"); } if (reward === "offline") { const gain = income() * 180; addMoney(gain); toast(`🌙 УДВОЕНО: +${fmt(gain)} ₽`); } save(); render(); }, onClose: startGameplay, onError: startGameplay } }); }
function maybeSpecial(now) { if (now < state.specialCooldown || Math.random() > .014 || !$("specialBtn").classList.contains("hidden")) return; state.specialUntil = now + SPECIAL_WINDOW; state.specialCooldown = now + 85000; $("specialBtn").classList.remove("hidden"); }
function catchSpecial() { if ($("specialBtn").classList.contains("hidden")) return; $("specialBtn").classList.add("hidden"); const gain = Math.max(500, income() * 25 + clickValue() * 80); addMoney(gain); state.parts += 25; toast(`🏎️ ТЕСТОВЫЙ АВТО: +${fmt(gain)} ₽, +25 🔩`); beep(1050, .12); save(); render(); }
function completeOrder() { const o = order(); if (state.parts < o.need) return toast(`Нужно ещё ${o.need - state.parts} 🔩`); state.parts -= o.need; addMoney(o.reward); state.parts += o.partReward; state.ordersDone++; toast(`📋 ЗАКАЗ ГОТОВ: +${fmt(o.reward)} ₽`); beep(900, .1); save(); render(); closeModal(); }
function prestige() { if (state.totalEarned < prestigeCost()) return; const meta = { prestige: state.prestige + 1, technologies: state.technologies, cars: state.cars, carQuality: state.carQuality, achievements: state.achievements, sound: state.sound, perfectAssemblies: state.perfectAssemblies, ordersDone: state.ordersDone, totalEarned: state.totalEarned }; state = { ...defaultState(), ...meta }; toast("🏆 НОВЫЙ ФИЛИАЛ ОТКРЫТ!"); save(); render(); }
function checkAchievements() { ACHIEVEMENTS.forEach((a, i) => { if (!state.achievements.includes(i) && a[3]()) { state.achievements.push(i); toast(`🏆 ${a[1]}`); } }); }

function renderWorkshops() { $("workshops").innerHTML = WORKSHOPS.map((w, i) => { const price = workshopPrice(i); return `<button class="workshop" data-workshop="${i}" ${state.money < price ? "disabled" : ""}><span class="icon">${w.icon}</span><div><b>${w.name} <em>LVL ${state.workshops[i]}</em></b><small>${w.desc} · +${fmt(w.rate * multiplier())} ₽/сек</small></div><em>${fmt(price)} ₽</em></button>`; }).join(""); document.querySelectorAll("[data-workshop]").forEach(b => b.addEventListener("click", () => buyWorkshop(Number(b.dataset.workshop)))); }
function render() { normalize(); const level = garageLevel(); const levelBefore = Math.pow(level - 1, 2) * 1000; const next = nextLevelAt(); const evo = currentEvolution(); const evoNext = nextEvolution(); $("money").textContent = `${fmt(state.money)} ₽`; $("income").textContent = `${fmt(income())} ₽/сек`; $("parts").textContent = `${fmt(state.parts)} 🔩`; $("garageLevel").textContent = `LVL ${level}`; $("levelProgress").textContent = `${fmt(state.totalEarned - levelBefore)} / ${fmt(next - levelBefore)}`; $("levelBar").style.width = `${clamp((state.totalEarned - levelBefore) / (next - levelBefore) * 100, 0, 100)}%`; $("garageName").textContent = evo.name; $("boostLabel").textContent = Date.now() < state.boostUntil ? "ТУРБО ×3" : "ТЕМП: ГОТОВ"; const hot = clamp((state.combo - 1) / 9 * 100, 0, 100); $("combo").textContent = `×${state.combo}`; $("comboBar").style.width = `${hot}%`; $("heatHint").textContent = state.combo >= 9 ? "ОСТАНОВИСЬ В ЖЁЛТОЙ ЗОНЕ — ИДЕАЛЬНОЕ ОХЛАЖДЕНИЕ!" : "Разгоняй темп, но не перегрей инструмент"; $("coolZone").style.left = `${Math.max(45, 66 - state.coolLevel * 4)}%`; $("dailyStatus").textContent = state.lastDaily === today() ? "ЗАВТРА" : "ГОТОВО"; $("crateStatus").textContent = Date.now() - state.lastCrate >= 3 * 3600000 ? "ГОТОВО" : "В ПУТИ"; const o = order(); $("orderStatus").textContent = `${fmt(Math.min(state.parts, o.need))}/${fmt(o.need)} 🔩`; $("powerPrice").textContent = `${fmt(powerPrice())} ₽`; $("critPrice").textContent = `${fmt(critPrice())} ₽`; $("coolPrice").textContent = `${fmt(coolPrice())} ₽`; $("powerInfo").textContent = `+1 · сейчас ${fmt(clickValue())} ₽`; $("critInfo").textContent = `${(4 + state.critLevel * 2.5).toFixed(1)}% шанс ×8`; $("coolInfo").textContent = `Зона +${state.coolLevel * 4}%`; $("techInfo").textContent = `${state.technologies.reduce((a,b) => a+b,0)} технологий`; $("powerUpgrade").disabled = state.money < powerPrice(); $("critUpgrade").disabled = state.money < critPrice(); $("coolUpgrade").disabled = state.money < coolPrice(); $("evolution").textContent = evo.name; $("evolutionSub").textContent = evoNext ? `${evo.sub} Следующая цель: ${fmt(evoNext.at)} ₽.` : "Ты построил настоящую автоимперию."; $("nextUnlock").textContent = evoNext ? `${fmt(evoNext.at)} ₽` : "MAX"; $("evolutionBar").style.width = `${evoNext ? clamp((state.totalEarned - evo.at) / (evoNext.at - evo.at) * 100, 0, 100) : 100}%`; $("prestigeCost").textContent = `${fmt(prestigeCost())} ₽`; $("prestigeBonus").textContent = `+${state.prestige * 25}%`; $("prestigeBtn").disabled = state.totalEarned < prestigeCost(); $("soundBtn").textContent = state.sound ? "🔊" : "🔇"; renderWorkshops(); }

function toast(text) { const el = $("toast"); el.textContent = text; el.classList.add("show"); clearTimeout(toast.timer); toast.timer = setTimeout(() => el.classList.remove("show"), 1900); }
function floatText(text, x, y, critical) { const el = document.createElement("div"); el.className = `float${critical ? " critical" : ""}`; el.textContent = text; el.style.left = `${x}px`; el.style.top = `${y}px`; document.body.append(el); setTimeout(() => el.remove(), 750); }
function beep(frequency, duration) { if (!state.sound) return; try { audioContext ||= new (window.AudioContext || window.webkitAudioContext)(); const osc = audioContext.createOscillator(); const gain = audioContext.createGain(); osc.frequency.value = frequency; gain.gain.value = .025; osc.connect(gain); gain.connect(audioContext.destination); osc.start(); gain.gain.exponentialRampToValueAtTime(.0001, audioContext.currentTime + duration); osc.stop(audioContext.currentTime + duration); } catch (_) {} }

function openModal(kind, data = {}) { stopGameplay(); $("modal").classList.remove("hidden"); const content = $("modalContent"); if (kind === "cars") { const list = CARS.map((car, i) => { if (state.cars[i]) return `<div class="vehicle"><span class="v-icon">${car.icon}</span><div><b>${car.name}</b><small>${car.rarity} · +${Math.round(car.bonus * (1 + state.carQuality[i]) * 100)}% к доходу</small></div><em>СОБРАНА</em></div>`; return `<button class="vehicle locked" data-car="${i}"><span class="v-icon">${car.icon}</span><div><b>${car.name}</b><small>${car.parts} 🔩 · ${car.rarity}</small></div><em>${state.parts >= car.parts ? "СОБРАТЬ" : `${state.parts}/${car.parts}`}</em></button>`; }).join(""); content.innerHTML = `<div class="modal-hero">🚗</div><h2>МОИ АВТОМОБИЛИ</h2><p>Собранные автомобили дают постоянный бонус к доходу. Сборка — шанс улучшить результат.</p>${list}`; document.querySelectorAll("[data-car]").forEach(b => b.addEventListener("click", () => startAssembly(Number(b.dataset.car)))); }
  else if (kind === "assembly") { const car = CARS[data.index]; content.innerHTML = `<div class="modal-hero">🔧</div><h2>СБОРКА: ${car.name}</h2><p>Нажми кнопку, когда маркер окажется в жёлтой зоне. Идеальная сборка добавит <b>+50% к бонусу машины</b>.</p><div class="assembly"><div class="meter"><i style="width:100%;opacity:.28"></i><span class="needle" id="needle"></span></div><button class="primary" id="assemblyBtn">СОБРАТЬ АВТОМОБИЛЬ</button></div>`; let position = 0; const timer = setInterval(() => { position = (position + 2.4) % 100; const needle = $("needle"); if (needle) needle.style.left = `${position}%`; }, 35); $("assemblyBtn").addEventListener("click", () => { clearInterval(timer); finishAssembly(data.index, position); }); }
  else if (kind === "orders") { const o = order(); content.innerHTML = `<div class="modal-hero">📋</div><h2>${o.name}</h2><div class="order-card"><h3>${o.text}</h3><p>Нужно: <strong>${o.need} 🔩</strong></p><p>Награда: <strong>${fmt(o.reward)} ₽</strong> и ${o.partReward} 🔩</p></div><button class="primary" id="orderComplete" ${state.parts >= o.need ? "" : "disabled"}>ВЫПОЛНИТЬ ЗАКАЗ</button>`; $("orderComplete").addEventListener("click", completeOrder); }
  else if (kind === "tech") { const techs = [["⚙️","Диагностический стенд","+8% к доходу"],["👷","Команда мастеров","+5% к доходу"],["📣","Реклама сервиса","+3% к доходу"]]; content.innerHTML = `<div class="modal-hero">🧠</div><h2>ТЕХНОЛОГИИ</h2><p>Технологии остаются после открытия нового филиала.</p>${techs.map((t,i) => `<button class="tech" data-tech="${i}"><span>${t[0]}</span><div><b>${t[1]} · LVL ${state.technologies[i]}</b><small>${t[2]}</small></div><em>${fmt(techPrice(i))} ₽</em></button>`).join("")}`; document.querySelectorAll("[data-tech]").forEach(b => b.addEventListener("click", () => { const i = Number(b.dataset.tech), p = techPrice(i); if (state.money < p) return toast(`Нужно ${fmt(p)} ₽`); state.money -= p; state.technologies[i]++; save(); render(); openModal("tech"); })); }
  else if (kind === "achievements") content.innerHTML = `<div class="modal-hero">🏆</div><h2>ДОСТИЖЕНИЯ</h2>${ACHIEVEMENTS.map((a,i) => `<div class="achievement"><span>${a[0]}</span><div><b>${a[1]}</b><small>${a[2]}</small></div><em>${state.achievements.includes(i) ? "✓" : "🔒"}</em></div>`).join("")}`;
  else if (kind === "offline") { content.innerHTML = `<div class="modal-hero">🌙</div><h2>ГАРАЖ РАБОТАЛ БЕЗ ТЕБЯ</h2><p>Пока тебя не было, сервис заработал <b>${fmt(data.gain)} ₽</b> за ${Math.floor(data.seconds / 60)} мин.</p><button class="primary" id="modalAction">ЗАБРАТЬ</button><button class="primary" id="doubleOffline">×2 ЗА ВИДЕО</button>`; $("modalAction").addEventListener("click", closeModal); $("doubleOffline").addEventListener("click", () => { closeModal(); showRewarded("offline"); }); }
  else content.innerHTML = `<div class="modal-hero">💡</div><h2>КАК ИГРАТЬ</h2><ol><li>Ремонтируй автомобиль, чтобы получать деньги и запчасти.</li><li>Покупай бизнесы: они приносят доход даже без кликов.</li><li>Собирай автомобили за запчасти и усиливай всю мастерскую.</li><li>Поймай жёлтую зону в сборке для идеального бонуса.</li><li>Открывай филиалы для постоянного роста.</li></ol><button class="primary" id="modalAction">В ГАРАЖ</button>`; const action = $("modalAction"); if (action) action.addEventListener("click", closeModal); }
function startAssembly(index) { const car = CARS[index]; if (state.parts < car.parts) return toast(`Нужно ещё ${car.parts - state.parts} 🔩`); openModal("assembly", { index }); }
function finishAssembly(index, position) { const perfectStart = Math.max(45, 66 - state.coolLevel * 4); const perfect = position >= perfectStart && position <= perfectStart + 13; state.parts -= CARS[index].parts; state.cars[index] = true; state.carQuality[index] = perfect ? .5 : position >= perfectStart - 12 && position <= perfectStart + 25 ? .1 : 0; if (perfect) state.perfectAssemblies++; toast(perfect ? "🔥 ИДЕАЛЬНАЯ СБОРКА! +50%" : "🚗 АВТОМОБИЛЬ СОБРАН!"); beep(perfect ? 1050 : 860, .13); checkAchievements(); save(); closeModal(); render(); }
function closeModal() { $("modal").classList.add("hidden"); startGameplay(); }

$("clicker").addEventListener("click", click); $("dailyBtn").addEventListener("click", claimDaily); $("crateBtn").addEventListener("click", claimCrate); $("orderBtn").addEventListener("click", () => openModal("orders")); $("turboBtn").addEventListener("click", () => showRewarded("turbo")); $("powerUpgrade").addEventListener("click", () => buyUpgrade("power")); $("critUpgrade").addEventListener("click", () => buyUpgrade("crit")); $("coolUpgrade").addEventListener("click", () => buyUpgrade("cool")); $("techBtn").addEventListener("click", () => openModal("tech")); $("prestigeBtn").addEventListener("click", prestige); $("specialBtn").addEventListener("click", catchSpecial); $("achievementsBtn").addEventListener("click", () => openModal("achievements")); $("helpBtn").addEventListener("click", () => openModal("help")); $("modalClose").addEventListener("click", closeModal); $("modal").addEventListener("click", e => { if (e.target.id === "modal") closeModal(); }); $("soundBtn").addEventListener("click", () => { state.sound = !state.sound; save(); render(); }); $("resetBtn").addEventListener("click", () => { if (confirm("Сбросить весь прогресс гаража?")) { localStorage.removeItem(SAVE_KEY); location.reload(); } });
document.querySelectorAll("[data-tab]").forEach(b => b.addEventListener("click", () => { document.querySelectorAll("[data-tab]").forEach(x => x.classList.remove("active")); b.classList.add("active"); if (b.dataset.tab === "business") $("businessPanel").scrollIntoView({ behavior: "smooth", block: "start" }); if (b.dataset.tab === "cars") openModal("cars"); if (b.dataset.tab === "orders") openModal("orders"); if (b.dataset.tab === "repair") $("repairScreen").scrollIntoView({ behavior: "smooth", block: "start" }); }));
document.addEventListener("visibilitychange", () => { if (document.hidden) { save(); stopGameplay(); } else startGameplay(); });
load(); render(); initYandexSDK(); let last = performance.now(), saveTime = 0, renderTime = 0; function tick(now) { const dt = Math.min(1, (now - last) / 1000); last = now; if (!document.hidden) addMoney(income() * dt); if (Date.now() > state.comboUntil) state.combo = 1; if (state.specialUntil && Date.now() > state.specialUntil) $("specialBtn").classList.add("hidden"); saveTime += dt; renderTime += dt; if (saveTime > 5) { saveTime = 0; save(); } if (renderTime > .15) { renderTime = 0; render(); } requestAnimationFrame(tick); } requestAnimationFrame(tick);
