const assert=require("node:assert/strict");
const fs=require("node:fs");
const vm=require("node:vm");
const code=fs.readFileSync("game.js","utf8");
const store=new Map();
const document={getElementById(){return null},querySelectorAll(){return[]},addEventListener(){},createElement(){return{style:{},classList:{add(){},remove(){}},remove(){}}},body:{append(){}}};
const context={console,document,Date,Math,JSON,Number,Array,Object,Set,Promise,Image:class{},innerWidth:1024,innerHeight:768,localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v),removeItem:k=>store.delete(k)},setTimeout(){return 1},clearTimeout(){},confirm(){return true},location:{reload(){}},performance:{now(){return 0}},window:undefined};
vm.createContext(context);vm.runInContext(code,context);
const run=s=>vm.runInContext(s,context);
run("state=defaultState()");
assert.equal(run("TOOL_NAMES.length"),30,"30 tools exist");
assert.equal(run("AUTO_NAMES.length"),40,"40 automation tiers exist");
assert.equal(run("ACHIEVEMENTS.length"),30,"30 achievements exist");
assert.ok(run("TASKS.length>=8"),"task catalogue exists");
assert.equal(run("state.money"),0,"new game starts with zero money");
run("click({clientX:10,clientY:10})");
assert.ok(run("state.money>0&&state.parts>0&&state.totalClicks===1"),"first repair pays");
run("state.money=100000;state.runEarned=100000;buyTool(0)");
assert.equal(run("state.tools[0]"),1,"tool purchase works");
assert.ok(run("clickValue()>1"),"tool improves click value");
run("state.money=100000;state.runEarned=100000;buyAutomation(0)");
assert.equal(run("state.automations[0]"),1,"automation purchase works");
assert.ok(run("income()>0"),"automation creates passive income");
const before=run("state.money");run("addMoney(income())");assert.ok(run("state.money>before"),"passive payout adds money");
run("save(true)");
assert.ok(store.has("garage_tycoon_idle_v3"),"save is written to localStorage");
const saved=JSON.parse(store.get("garage_tycoon_idle_v3"));assert.equal(saved.automations[0],1,"automation persists");
const normalized=run("normalizeState({money:-10,parts:'bad',tools:[-2,'bad'],automations:[-1],selectedGarage:99,equippedCar:99})");
assert.equal(normalized.money,0,"invalid money is normalized");
assert.equal(normalized.parts,0,"invalid parts are normalized");
assert.equal(normalized.tools[0],0,"invalid tool levels are normalized");
assert.equal(normalized.automations[0],0,"invalid automation levels are normalized");
assert.equal(normalized.selectedGarage,4,"garage index is clamped");
assert.equal(normalized.equippedCar,0,"invalid car falls back to first car");
run("state.money=123;state.parts=456;state.tools[0]=2;state.automations[0]=3;state.achievements=[0,1];save(true);resetGame()");
assert.equal(run("state.money"),0,"reset clears money");
assert.equal(run("state.parts"),0,"reset clears parts");
assert.equal(run("state.tools.reduce((a,b)=>a+b,0)"),0,"reset clears tools");
assert.equal(run("state.automations.reduce((a,b)=>a+b,0)"),0,"reset clears automation");
assert.equal(run("state.achievements.length"),0,"reset clears achievements");
console.log("Idle clicker core tests passed.");
